[package]
name = "clark"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]
proc-macro = true

[dependencies]
ctrlc = "3.5.1"

[dev-dependencies]


[[example]]
name = "hello_world"
path = "examples/hello_world.rs"

[[example]]
name = "main"
path = "examples/main.rs"
